[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar build/libs/platzi-market-1.0.jar"

[build.env]
NIXPACKS_JDK_VERSION = "21"
JAVA_HOME = "/opt/java/openjdk"
PATH = "/opt/java/openjdk/bin:${PATH}"